# Tên của workflow, sẽ hiển thị trong tab "Actions" của repo
name: Build and Push Docker Image to GHCR

# Cấu hình khi nào workflow sẽ chạy
on:
  # Chạy khi có push code lên branch 'main'
  push:
    branches: [ "main" ]
  # Cho phép chạy thủ công từ tab Actions
  workflow_dispatch:

# Các công việc (jobs) sẽ được thực thi
jobs:
  build-and-push-image:
    # Chạy trên một máy ảo Ubuntu mới nhất do GitHub cung cấp
    runs-on: ubuntu-latest

    # Cấp quyền cho workflow để ghi vào Packages (GHCR)
    # Đây là bước quan trọng và an toàn, không cần dùng PAT (Personal Access Token)
    permissions:
      contents: read
      packages: write

    steps:
      # Bước 1: Checkout code từ repository
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite
          coverage: none

      - name: Install Composer dependencies
        run: |
          composer install --prefer-dist --no-interaction --no-progress
          ls -la ./vendor/laravel/sail/runtimes/8.2/

      # --- PHẦN CHỈNH SỬA DOCKERFILE TẠM THỜI ---
      - name: Temporarily modify Dockerfile to install SQL Server drivers
        run: |
          # Đường dẫn đến Dockerfile gốc trong vendor
          DOCKERFILE_PATH="./vendor/laravel/sail/runtimes/8.2/Dockerfile"

          echo "--- Dockerfile before modification ---"
          cat $DOCKERFILE_PATH
          
          # Sử dụng `sed` để thêm các lệnh cài đặt driver vào Dockerfile
          # Lệnh này tìm dòng `&& apt-get install -y \` và chèn các lệnh của chúng ta vào ngay sau đó.
          # `\` dùng để xuống dòng, `\t` để thụt lề cho đẹp.
          sed -i '/&& apt-get install -y \\/a \
          # Install deps & add Microsoft repo \
          \t&& apt-get install -y gnupg curl apt-transport-https lsb-release \\
          \t&& curl -fsSL https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor -o /usr/share/keyrings/microsoft-prod.gpg \\
          \t&& curl -fsSL https://packages.microsoft.com/config/ubuntu/22.04/prod.list > /etc/apt/sources.list.d/mssql-release.list \\
          \t&& apt-get update \\
          # Install ODBC and SQL Server Driver \
          \t&& ACCEPT_EULA=Y apt-get install -y --no-install-recommends unixodbc-dev msodbcsql18 \\' $DOCKERFILE_PATH

          # Sử dụng `sed` để thêm các lệnh cài đặt và kích hoạt extension PHP
          # Lệnh này tìm dòng `&& pecl install redis igbinary msgpack \\` và chèn lệnh của chúng ta vào ngay sau.
          sed -i '/&& pecl install redis igbinary msgpack \\/a \
          # Install PHP extensions for SQL Server \
          \t&& pecl install sqlsrv pdo_sqlsrv \\' $DOCKERFILE_PATH
          
          # Lệnh này tìm dòng `&& docker-php-ext-enable redis igbinary msgpack \\` và chèn lệnh kích hoạt.
          sed -i '/&& docker-php-ext-enable redis igbinary msgpack \\/a \
          # Enable PHP extensions for SQL Server \
          \t&& docker-php-ext-enable sqlsrv pdo_sqlsrv \\' $DOCKERFILE_PATH

          echo "--- Dockerfile after modification ---"
          cat $DOCKERFILE_PATH
      
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Bước 2: Đăng nhập vào GitHub Container Registry (ghcr.io)
      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          # github.repository_owner là chủ sở hữu repo (diepxuan)
          username: ${{ github.repository_owner }}
          # GITHUB_TOKEN là một token tạm thời được tạo tự động cho mỗi lần chạy workflow
          password: ${{ secrets.GITHUB_TOKEN }}

      # Bước 3: Trích xuất metadata (tags và labels) cho Docker image
      # Action này sẽ tự động tạo các tag hợp lý như 'latest', 'sha-<mã commit>'
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository }} # ghcr.io/diepxuan/portal
          tags: |
            # type=semver: tạo tag phiên bản khi push git tag, ví dụ: v1.2.3
            type=semver,pattern={{version}}
            
            # type=edge: tạo tag 'latest' khi push lên branch 'main'
            type=edge,branch=main
            
            # type=ref,event=branch: tạo tag theo tên branch, ví dụ: main
            type=ref,event=branch
            
            # QUAN TRỌNG: Ghi đè để tạo tag 'latest' khi push lên branch 'main'
            # (branch mặc định của repo)
            type=raw,value=latest,enable={{is_default_branch}}

      # Bước 4: Build và push Docker image
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          # QUAN TRỌNG: `context` là thư mục gốc của project Laravel của bạn
          # vì Dockerfile của Sail có thể tham chiếu đến các file từ thư mục gốc.
          context: ./vendor/laravel/sail/runtimes/8.2
          
          # QUAN TRỌNG: Chỉ định đường dẫn chính xác đến Dockerfile
          file: ./vendor/laravel/sail/runtimes/8.2/Dockerfile

          push: true # Đẩy image sau khi build thành công
          tags: ${{ steps.meta.outputs.tags }} # Sử dụng các tag đã tạo ở bước trên
          labels: ${{ steps.meta.outputs.labels }} # Gắn các label đã tạo ở bước trên
          
          # Dockerfile build args
          build-args: |
            WWWUSER=1000
            WWWGROUP=1000
          # QUAN TRỌNG: Thêm dòng này để build cho cả 2 kiến trúc
          # platforms: linux/amd64,linux/arm64
