# Tên của workflow, sẽ hiển thị trong tab "Actions" của repo
name: Build and Push Docker Image to GHCR

# Cấu hình khi nào workflow sẽ chạy
on:
  # Chạy khi có push code lên branch 'main'
  push:
    branches: [ "main" ]
  # Cho phép chạy thủ công từ tab Actions
  workflow_dispatch:

# Các công việc (jobs) sẽ được thực thi
jobs:
  build-and-push-image:
    # Chạy trên một máy ảo Ubuntu mới nhất do GitHub cung cấp
    runs-on: ubuntu-latest

    # Cấp quyền cho workflow để ghi vào Packages (GHCR)
    # Đây là bước quan trọng và an toàn, không cần dùng PAT (Personal Access Token)
    permissions:
      contents: read
      packages: write

    steps:
      # Bước 1: Checkout code từ repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Bước 2: Đăng nhập vào GitHub Container Registry (ghcr.io)
      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          # github.repository_owner là chủ sở hữu repo (diepxuan)
          username: ${{ github.repository_owner }}
          # GITHUB_TOKEN là một token tạm thời được tạo tự động cho mỗi lần chạy workflow
          password: ${{ secrets.GITHUB_TOKEN }}

      # Bước 3: Trích xuất metadata (tags và labels) cho Docker image
      # Action này sẽ tự động tạo các tag hợp lý như 'latest', 'sha-<mã commit>'
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository }} # ghcr.io/diepxuan/portal

      # Bước 4: Build và push Docker image
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: . # Sử dụng context là thư mục gốc của repo
          push: true # Đẩy image sau khi build thành công
          tags: ${{ steps.meta.outputs.tags }} # Sử dụng các tag đã tạo ở bước trên
          labels: ${{ steps.meta.outputs.labels }} # Gắn các label đã tạo ở bước trên
